### ISSUE TITLE
Context DOI redirect is failing in JSON-LD playground, JSON-LD libraries

### ISSUE THREAD

**Issue by gothub** [codemeta/codemeta#125] opened 2017-01-06 19:49 UTC
When the JSON-LD playground and other JSON-LD libraries (ruby) see the remote context in
one of our CodeMeta documents, i.e.:
```
"@context":"https://doi.org/10.5063/SCHEMA/CODEMETA-1.0",
```
They send a HTTP GET request with "Accept: application/ld+json" to read the remote context.
This returns the Datacite 'metadata' page

http://data.datacite.org/10.5063%2FSCHEMA%2FCODEMETA-1.0

and not the DOI resolution of 

https://raw.githubusercontent.com/codemeta/codemeta/1.0/codemeta.jsonld

The DOI entry is typed as 'text/json' at http://ezid.cdlib.org/id/doi:10.5063/SCHEMA/CODEMETA-1.0

I'm wondering if adding the type `application/ld+json` to the DOI entry will resolve this problem.

For more details, see https://github.com/json-ld/json-ld.org/issues/447

**Comment by cboettig** [comment] 2017-01-17 00:07
@gothub Any luck resolving this one?

**Comment by gothub** [comment] 2017-01-17 00:51
@cboettig Not yet. Rereading this issue I'm seeing that I didn't make it very explicit
that I'd like @mbjones to change the type field in the DOI entry (from EZID) then I can check if this
will resolve the problem. If it doesn't then I'll need to talk to our friends at DataCite to see
if they can help.

**Comment by mbjones** [comment] 2017-01-17 02:28
Ok, on a flight now, will look into it tomorrow.

Matt

**Comment by mbjones** [comment] 2017-01-17 22:10
Tried changing the type to `application/ld+json` with no effect.

Reading the [resolver docs at DataCite](http://citation.crosscite.org/docs.html), its now clear that their advertised behavior is:

1) return the resource redirect if `text/html` is requested
2) return a formatted version of the metadata if any other content type is requested

In particular, they say:

> DOI resolvers use content negotiation to provide different representations of __metadata__ associated with DOIs.

Whereas, like most web tools, the JSON-LD libraries expect content negotiation to return the actual resource in the requested format, not metadata about the resource.  So, there is a fundamental mismatch here in how these systems work.

**Comment by gothub** [comment] 2017-01-17 22:45
@mfenner could you comment on this? Is there any way that we can use a DOI for the CodeMeta JSON-LD context file, when software libraries that parse and operate on this file are requesting a resource as `application/ld+json`?

**Comment by mfenner** [comment] 2017-01-18 00:15
Late last year DataCite started to provide content negotiation for JSON-LD and would return schema.org metadata, e.g. `curl -LH "Accept: application/ld+json" https://doi.org/10.5063/SCHEMA/CODEMETA-1.0`. This is documented at http://citation.crosscite.org/docs.html.

I have to look into how content negotiation works if there is also `application/ld+json` registered as media type with an associated URL. If the mime-type registered for the DOI has higher priority, we have the problem that users can't get to the schema.org/JSON-LD metadata.

This raises the bigger issue of whether `application/ld+json` is the correct mime-type for schema.org in JSON-LD format, or whether we should use something like `application/vnd.datacite.ld+json`. Unfortunately I think that the short-term solution is to use the URL instead of the DOI for the context URI, but we need to think about how to properly sort this out.

**Comment by mbjones** [comment] 2017-01-18 00:40
@mfenner The reason we wanted to use the DOI as the context URI is that many codemeta documents in the wild will hardcode this context URI, and so we want it to be permanent -- we don't want to rely on a `raw.githubusercontent.com` URI for the context, as its longevity is unlikely.  So, if a DOI won't work here, then we may have to switch to using a PURL-style URI that we can control redirection on.  But we'd much prefer a DOI.

@cboettig @gothub thoughts on other trajectories we could take?

**Comment by cboettig** [comment] 2017-01-18 00:49
If a DOI won't work, I think PURL would be the way to go; we've confirmed that works with purl.org though Matt you're probably familiar with some other options so I'm happy to follow your lead here.  purl.org seems to be a very common choice for ontologies so I suppose it's not too strange a choice for a jsonld context file.

Having to be rescued by internet archive wasn't confidence-inspiring for purl.org either, but I suppose that it should be reasonably reliable now.  I agree that having `raw.githubusercontent.com`  doesn't feel viable.  

@mfenner thanks for weighing in here and definitely keep us in the loop about where DataCite is headed with this.

**Comment by mfenner** [comment] 2017-01-18 06:19
I think before we rule out DOIs (which I think is a good use case) I need to take a closer look at that content negotiation part, as this will affect other use cases. It would, for example, help me to find more specific mime types than `application/ld+json` for schema.org JSON-LD.

**Comment by mfenner** [comment] 2017-01-18 10:34
I have updated the DataCite content resolver to use `application/vnd.schemaorg.ld+json` for showing schema.org metadata in JSON-LD format,  requests with an `application/ld+json` accept header no longer redirect to the metadata.

If this still doesn't work, you have to register `application/ld+json` and https://raw.githubusercontent.com/codemeta/codemeta/1.0/codemeta.jsonld with the DOI (via EZID in your case I guess).

**Comment by gothub** [comment] 2017-01-18 14:32
@mfenner this sample request:

`curl -v -X GET "https://doi.org/10.5063/SCHEMA/CODEMETA-1.0" -H "Accept: application/ld+json"`

still returns the HTTP 303 Location as the DataCite metadata landing page and not the context file location:

```
< HTTP/1.1 303 See Other
< Server: Apache-Coyote/1.1
< Vary: Accept
< Location: http://data.datacite.org/10.5063%2FSCHEMA%2FCODEMETA-1.0
< Expires: Wed, 18 Jan 2017 15:07:23 GMT
< Content-Type: text/html;charset=utf-8
< Content-Length: 197
< Date: Wed, 18 Jan 2017 14:26:24 GMT
```

Do we need to change something else with the EZID entry at 
'http://ezid.cdlib.org/id/doi:10.5063/SCHEMA/CODEMETA-1.0'

**Comment by mfenner** [comment] 2017-01-18 14:37
You need to allow redirection (with curl -L): 

```
curl -LH "Accept: application/ld+json" -v https://doi.org/10.5063/SCHEMA/CODEMETA-1.0
```

It still doesn't work because `application/ld+json` does not seem to be registered with a redirect URL for that DOI.

**Comment by mbjones** [comment] 2017-01-18 16:36
@mfenner I'm not sure how to do that -- EZID does not seem to provide an API method for setting a URI for a particular content-type, only for providing one URL generally.  Seems like the [DataCite DOI API](https://mds.datacite.org/static/apidoc#tocAnchor-15) is the same way, as POST operations to https://mds.datacite.org/doi  only take `doi` and `url` parameters, and not a content-type qualifier.  Is there another API I am missing?  Or is there some way to add a redirect URL for `application/ld+json` to the metadata somehow?

**Comment by mfenner** [comment] 2017-01-18 17:56
In the DataCite MDS API you do this via the https://mds.datacite.org/media endpoint, I am sure EZID provides something similar.

**Comment by mbjones** [comment] 2017-01-19 10:28
OK, I see how it works on the DataCite side.  Not seeing something similar for EZID, but I will check with them.

**Comment by gothub** [comment] 2017-01-19 17:29
@mbjones I'm not able to view that DataCite page (requires login) so am not sure what to check for
in EZID. I had a look at their api docs and didn't see anything relevant, so please post here what you
find out then I can use the [EZID api ](http://ezid.cdlib.org/doc/apidoc.html) to update the test DOI that I've recreated, and test resolution with that.

**Comment by cboettig** [comment] 2017-01-24 19:07
@mbjones Any update on this? I know there's a lot on your plate right now.

@mfenner thanks for the help, does sound promising that we'll get this to work with a DOI.

**Comment by mbjones** [comment] 2017-01-24 19:50
Nope, haven't had a chance to check in with EZID folks about whether they have an equivalent of the DataCite media API.  Do you want to contact them @cboettig?

**Comment by gjanee** [comment] 2017-01-24 20:33
I'm sorry to report that EZID does not currently support multiple URIs, or indexing those URIs by content type.  We've talked about adding that, but there hasn't been a compelling enough use case (until now!).

**Comment by gjanee** [comment] 2017-01-24 20:50
To qualify my response above, I don't feel confident that I'm understanding the underlying problem here.  My reading is that there is a resource at a DOI that has a content type X, and which content type is recorded in the DataCite metadata, and a client is resolving that DOI with a header of "Accept: X" and it's not getting the content.  Instead it's getting some metadata.  If that's correct... what change would be in EZID's scope here?  Seems more like a resolver issue.

**Comment by mfenner** [comment] 2017-01-24 21:23
I see three ways to resolve this:

* you double-check whether you really need to provide "application/ld+json" in your request. Everything would work fine without accept header
* EZID starts supporting the DataCite MDS functionality of registering custom URLs for specific content types
* DataCite makes a change to its DOI content resolver: use the default URL if the content type is not recognized instead of returning a 406 error. I will check with Crossref to make sure we provide consistent behavior in DOI content negotiation.

**Comment by mfenner** [comment] 2017-01-24 22:03
It seems that Crossref is also returning a 406 status if the content type is not recognized. And Github is ignoring the accept header and is returning `text/plain`: `curl -LH "Accept: application/ld+json" https://raw.githubusercontent.com/codemeta/codemeta/1.0/codemeta.jsonld -v`.  And that the DOI proxy forwards the accept header to Github: `curl -LH "Accept: application/ld+json, text/html" https://doi.org/10.5063/SCHEMA/CODEMETA-1.0 -v` There is more than one way to solve this, but I am happy to help on the DataCite end for maximal flexibility.

**Comment by gothub** [comment] 2017-01-25 00:55
@mfenner What is the `default URL` you mentioned in bullet 3 above: `DataCite makes a change...`? 

I think it would be difficult to have all needed JSON LD libraries change the way they are
fetching remote context files via a redirect (DOI in our case) - their initial request specifies
 "Accept: application/ld+json" and then the library sees that the http return status is 303, then they read the 'Location' field of the http result header and that must be 'https://raw.githubusercontent.com/codemeta/codemeta/1.0/codemeta.jsonld', otherwise the retrieveal of the remote context file fails.

This is the behaviour for the javascript and ruby JSON-LD libraries, I haven't checked others.
I'm hoping that the DOI resolution can support this same behaviour.

**Comment by mbjones** [comment] 2017-01-25 03:35
To highlight, as @gothub said, we don't control the client code libraries,
so whatever we do we have to handle their request for "application/ld+json"
and return the codemeta file, and not the DOI metadata about the file.
Seems like the media API is the way to acheive that, if only it were
accessible through EZID.  @gjanee Could EZID do a custom media API request
for this one DOI while a more general solution is worked out?

**Comment by gjanee** [comment] 2017-01-25 05:20
For any finite set of DOIs I think I can manually use DataCite's media API and add whatever content types and URIs you need as an interim solution, without breaking EZID.  Would that help you out?  Peter, feel free to call me, x8453

**Comment by mfenner** [comment] 2017-01-25 08:54
@gjanee it would be great if you could do that in this particular case. Option 3 would take a while because of a dependency that requires some work for DataCite. @gothub with default URL I mean the URL registered for the DOI, https://raw.githubusercontent.com/codemeta/codemeta/1.0/codemeta.jsonld in this case.

**Comment by cboettig** [comment] 2017-02-06 21:17
@gothub @gjanee Were we able to resolve the content-type resolution issue for json-ld for this one DOI case?

**Comment by gjanee** [comment] 2017-02-06 21:35
Instead of "finite" I should have used the word "static".  As in, I would need a list of DOIs you want this done to.

**Comment by cboettig** [comment] 2017-02-06 21:55
@gjanee Ah, sorry for the confusion, the DOI in question is given higher up in the issue thread. My apologies.  It is: https://doi.org/10.5063/SCHEMA/CODEMETA-1.0  

That's the only DOI we would need at this point.  When we have a new version to release we'll need to repeat this with the new DOI.  Thanks much!

**Comment by gjanee** [comment] 2017-02-06 22:06
@cboettig And just so I'm clear, you'd like that DOI's target URL (https://raw.githubusercontent.com/codemeta/codemeta/1.0/codemeta.jsonld) to also be associated with MIME type application/ld+json?

**Comment by cboettig** [comment] 2017-02-06 22:08
yup, I'm pretty sure that's correct. (@gothub has been doing the implementation on this one but I think that should do it).

**Comment by cboettig** [comment] 2017-02-06 22:18
@gjanee Thanks!

When I do:

```
curl -LH "Accept: application/ld+json" https://doi.org/10.5063/SCHEMA/CODEMETA-1.0
```

I still get an error (406, "Not Acceptable"): 

> The resource identified by this request is only capable of generating responses with characteristics not acceptable according to the request "accept" headers.

```
<html><head><title>Apache Tomcat/7.0.68 (Ubuntu) - Error report</title><style><!--H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}HR {color : #525D76;}--></style> </head><body><h1>HTTP Status 406 - Not Acceptable</h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u>Not Acceptable</u></p><p><b>description</b> <u>The resource identified by this request is only capable of generating responses with characteristics not acceptable according to the request "accept" headers.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.68 (Ubuntu)</h3>
```

Any ideas?  Maybe the changes just haven't propagated yet or is there something else that needs to be changed to accept that MIME type?

**Comment by gothub** [comment] 2017-02-06 22:28
@cboettig Try,

```
curl -v -L "Accept: application/ld+json" https://doi.org/10.5063/SCHEMA/CODEMETA-1.0
```

It looks like the redirect is working correctly with curl. I'm still having trouble with the JSON-LD
playground and ruby library, but that may be either a caching problem or a problem with the library.
So, the initial test shows that the EZID is working.

I'll continue looking into the JSON LD playground trouble.

Thanks @gjanee

**Comment by mfenner** [comment] 2017-02-06 22:43
@gothub `curl -v -L "Accept: application/ld+json" https://doi.org/10.5063/SCHEMA/CODEMETA-1.0` works because there is no content negotiation happening (`-H` is missing), and the DOI is resolved normally. The correct command is the one used by @cboettig, but DataCite is not finding the content-type registered for the DOI. @gjanee the media-type you registered in MDS looks correct. Let me look further into this.

**Comment by gothub** [comment] 2017-02-06 22:52
@mfenner yep, thanks @mfenner

**Comment by cboettig** [comment] 2017-02-17 19:29
@mfenner Any news on what might be going wrong here with the DOI resolution for JSON-LD?

**Comment by mfenner** [comment] 2017-02-23 09:22
@cboettig I had looked into this, but there seems to be some deeper issue that I don't understand yet. I am in the process of rewriting the DataCite content negotiation service, and I will fix this as part of this work. Unfortunately this means that this will taken another few weeks.

**Comment by cboettig** [comment] 2017-02-23 17:39
@mfenner thanks, sounds good!  keep us posted.

**Comment by mfenner** [comment] 2017-02-27 11:41
Somewhat related to this: could you imagine using a different, more specific content type? That would work better with DataCite content negotiation, but also in other cases where JSON-LD is used in multiple ways. And you can provide JSON-LD as fallback. For example:
```
curl -LH "Accept: application/vnd.codemeta.ld+json, application/ld+json" https://doi.org/10.5063/SCHEMA/CODEMETA-1.0
```

**Comment by gothub** [comment] 2017-02-27 17:25
@mfenner Sounds fine, but just curious what the use case is for differentiating JSON-LD
from CodeMeta JSON-LD (via the vender specific MIME type)? The content delivered won't be
different between the two types, and parsing of the delivered document won't be different. 

The client making the request with the CodeMeta JSON-LD type will  know however, that what they are getting is a software description, yes?

**Comment by mfenner** [comment] 2017-02-27 17:59
@gothub this is important for content negotiation where content is available in two different representations that both use JSON-LD serialization, but are otherwise different. Codemeta JSON-LD and schema.org JSON-LD that we had here is just one example, and going forward there will probably more of those. You get different metadata for these two, even if they are about the same thing, software in this case. Since codemeta is all about crosswalking different metadata standards, a specific mime type for codemeta would make sense to me.

**Comment by gjanee** [comment] 2017-02-27 18:21
Isn't the fundamental problem here that DataCite/Crossref are using MIME types as a proxy for semantics?  So because DataCite uses JSON-LD to signal "give me the DataCite metadata", nobody else in the world can use that MIME type as a descriptor for their own data?

**Comment by cboettig** [comment] 2017-03-29 23:26
@mfenner Any update on this issue / the DataCite CN service rewrite?  is the basic conclusion that we should have to change the mime type in the EZID record?  I think I'm with @gjanee on this that it seems strange to need a codemeta-specific mime type, particularly for json-ld where it seems the context should define the semantics (isn't that the whole point?)  Maybe I'm just not thinking about this properly.

**Comment by mfenner** [comment] 2017-03-30 10:42
@cboettig I have a hard deadline for a major update of the DataCite content negotiation by the end of April. Will jump into the work after next week, which is the Research Data Alliance Plenary.

Regarding the second part of your message, this is just how content negotiation works, not just DataCite's. You tell the user what he is getting before he starts parsing your JSON-LD. You can provide this information in a header, see http://signposting.org/bibliographic_metadata/ for a good example. While you can use something like `application/xml` or `application/ld+json`, it makes the content negotiation less useful. The other issue is that you use up `application/json+ld` for codemeta metadata. What do you do if someone writes a software package where he also wants to use `application/ld+json`, but for something else, e.g. schema.org metadata? In the end it is of course up to you, DataCite will after the rewrite pass through the content type, and you will no longer need to register any content type with EZID.

**Comment by cboettig** [comment] 2017-03-30 16:12
@mfenner Sounds great, good luck with the CN rewrite and look forward to seeing what we get.

Regarding the MIME type, my point (and I think @gjanee 's) is that the MIME type here should really be `application/ld+json`.  That contains the essential information for the developer to use the right parser.  The whole point is that this is *linked data* and not just raw json, so the `@context` provides fully resolved meaning for any of the terms.  Of course we can mix and match schemas in json-ld (codemeta already uses schema.org, among others, in the `@context`: https://github.com/codemeta/codemeta/blob/master/codemeta.jsonld.)  I'm not sure what the meaning of the MIME type `application/vnd.schemaorg.ld+json` is meant to be -- does this imply a JSON-LD file in which the only context is `schema.org`?  

After all, linked data is just collection of triples, if the developer desires a particular tree structure to simplify parsing they can specify that using JSON-LD framing, which would filter out terms that don't match the frame.

**Comment by mfenner** [comment] 2017-03-30 19:02
@cboettig let's pick up the discussion some other time. Top priority is to get the content negotiation working for you.

**Comment by mfenner** [comment] 2017-04-17 13:20
@cboettig or @gjanee have you made any changes to the media type registered for https://doi.org/10.5063/SCHEMA/CODEMETA-1.0? When I accidentally checked today, I found `application/json` rather than `application/ld+json`. 

If this wasn't changed recently, it explains why content negotiation for `application/ld+json` wasn't working when we checked in February. I just changed `application/json` to `application/ld+json`, but it will not go live until tomorrow when we have updated the DataCite Solr index.

I hope to launch a stage version of the updated DataCite DOI content negotiation later this week. One new feature relevant here will be to return codemeta metadata for any DOI (useful of course only for software). For this you need to request the content type `application/vnd.codemeta.ld+json`, and you can try it out now using https://github.com/datacite/bolognese via the command line. As I tried to explain earlier in this thread, DOI content negotiation works via the media type and not by inspecting the content. For this reason we need something specific for codemeta rather than the generic `application/ld+json`.

What you can also do is use https://github.com/datacite/bolognese to convert codemeta metadata into a variety of formats, not only DataCite XML, but also for example bibtex, citeproc JSON, schema.org or turtle.

**Comment by gjanee** [comment] 2017-04-17 15:27
I haven't done anything, and when I look in MDS, it's application/ld+json as last updated back in February.

**Comment by mfenner** [comment] 2017-04-17 15:31
I just directly changed the entry in the database. We will see tomorrow after Solr indexing, whether that resolves the issue.

**Comment by mfenner** [comment] 2017-04-18 08:50
Unfortunately that didn't fix it. But I deployed the new version of DataCite content negotiation to our staging server and it works as expected:

``` 
curl -LH "Accept: application/ld+json" https://data.test.datacite.org/10.5063/SCHEMA/CODEMETA-1.0
```
Once this is deployed to production in a week or so, the following should finally work (requests to doi.org for content types other than `text/plain` or `text/html` are forwarded to https://data.datacite.org), and doesn't require registration of the media type via EZID:

``` 
curl -LH "Accept: application/ld+json" https://doi.org/10.5063/SCHEMA/CODEMETA-1.0
```

**Comment by cboettig** [comment] 2017-04-18 13:54
Awesome Martin, thanks!

**Comment by mfenner** [comment] 2017-05-10 06:46
We launched our rewritten DataCte DOI content negotiation service yesterday, and the following finally works as expected:

```
curl -LH "Accept: application/ld+json" https://doi.org/10.5063/SCHEMA/CODEMETA-1.0
```

You can also do these requests to have the DataCite metadata returned as codemeta or schema.org/JSON-LD:

```
curl -LH "Accept: application/vnd.codemeta.ld+json" https://doi.org/10.5063/SCHEMA/CODEMETA-1.0
curl -LH "Accept: application/vnd.schemaorg.ld+json" https://doi.org/10.5063/SCHEMA/CODEMETA-1.0
```

**Comment by mbjones** [comment] 2017-05-10 21:20
@mfenner Awesome, and thanks!

**Closed** 2017-05-12 20:55 UTC
