### ISSUE TITLE
how to generate codemeta.json from python

### ISSUE THREAD

**Issue by danielskatz** [codemeta/codemeta#190] opened 2018-08-30 15:30 UTC
I know there's a python tool to generate a codemeta.json file, but it's not listed on https://codemeta.github.io/tools/ or http://codemeta.github.io/user-guide/

Also, that tool does not generate a file that includes ORCIDs, which it probably should

**Comment by cboettig** [comment] 2018-08-30 17:12
@danielskatz indeed, still needs to be done (duplicate of #182). 

Re ORCIDs in python version, maybe you can open an issue at https://github.com/proycon/codemetapy/issues ?

Thanks!

**Closed by cboettig** 2018-08-30 17:12 UTC
