### ISSUE TITLE
Proposal for author roles in CodeMeta v3

### ISSUE THREAD

**Issue by moranegg** [codemeta/codemeta#240] opened 2020-04-03 14:16 UTC
The question of authorship and contribution roles in the scholarly ecosystem has been addressed in different ways, yet software remains an uncharted terrain.
In the CRedit for example, software is a unique role that combines all roles related to software authorship (see https://casrai.org/credit/ )

We know that the situation with software development is a bit more complex and can't be resumed in the distinction between `author` and `contributor`.

Recently the Inria research center's citation WG has published the following article with a specific taxonomy concerning software roles:
> Pierre Alliez, Roberto Di Cosmo, Benjamin Guedj, Alain Girault, Mohand-Said Hacid, Arnaud Legrand, Nicolas Rougier. Attributing and Referencing (Research) Software: Best Practices and Outlook From Inria. Computing in Science > Engineering, 22 (1), pp. 39-52, 2020, ISSN: 1558-366X. https://dx.doi.org/10.1109/MCSE.2019.2949413 also available  https://hal.archives-ouvertes.fr/hal-02135891

We want to find a way to integrate the identified roles in the CodeMeta vocabulary and in schema.org.
To that end we propose on using the  [Role](https://schema.org/Role) class under `author`, and link it to a [Person](https://schema.org/Person), as specified in the [blog post on roles](http://blog.schema.org/2014/06/introducing-role.html).

List of roles: 
- Design (algorithm)
- Architecture 
- Debugging
- Maintenance
- Coding
- Documentation
- Testing
- Support
- Management

Here is an example:

```json
{
    "@context": "https://doi.org/10.5063/schema/codemeta-2.0",
    "@type": "SoftwareSourceCode",
    "name": "Foo Software",
    "author": [
        {
            "@type": "Role",
            "roleName": "Design",
            "startDate": "2000",
            "endDate": "2002",
            "author": {
                "@type Person",
                "@id": "http://example.org/~jdupont",
                "givenName": "John",
                "familyName": "Dupont",
                "affiliation": [
                    {
                        "@type": "Organization",
                        "name": "CNRS"
                    },
                    {
                        "@type": "Organization",
                        "name": "Inria"
                    },
                    {
                        "@type": "Organization",
                        "name": "Université de Paris"
                    }
                ]
            }
        },
        {
            "@type": "Role",
            "roleName": "Coding",
            "startDate": "2000",
            "endDate": "2002",
            "author": {
                "@id": "http://example.org/~jdupont"
            }
        },
        {
            "@type": "Role",
            "roleName": "Documentation",
            "startDate": "2000",
            "endDate": "2002",
            "author": {
                "@id": "http://example.org/~jdupont"
            }
        }
    ]
}
```

Note that I added an ID to avoid duplicating the person's data

**Comment by npch** [comment] 2020-04-03 16:02
I think it makes sense to have it as a role, under author. In many cases, knowing the list of authors is enough, but this enables information around roles (and when these roles were active) to be expressed in CodeMeta if available.

**Comment by cboettig** [comment] 2020-04-03 16:42
This makes sense to me as well.  Is this pattern being used now to describe CRedit roles in schema.org descriptions of journal publications as well?  It makes sense to me that we be as consistent as possible.

**Comment by mbjones** [comment] 2020-04-07 22:49
I'm all for adding role as well.  The irony is that the first version of CodeMeta had a role field for all people entries, and our two workshops proposed and implemented removing the role from the vocabulary.  So we've come full circle, as many metadata discussions seem to do. 

@cboettig , you argued for and implemented the opposite approach to remove role from our prior agent/role implementation in issue #135 . That thread has some useful discussion, primarily on the reuse of existing role taxonomies, such as [ISO role codes](http://www.ngdc.noaa.gov/metadata/published/xsd/schema/resources/Codelist/gmxCodelists.xml#CI_RoleCode) and other well-established role taxonomies that are in use in the data world.  If we are to reintroduce roles, I vote to make it possible to use these existing taxonomies that are in widespread use in the data repository landscape.

On another note, the science-on-schema.org group has made [specific recommendations on how to represent Roles](https://github.com/ESIPFed/science-on-schema.org/blob/master/guides/Dataset.md#roles-of-people) that are consistent with schema.org's recommended approach as described in their [Role blog post](http://blog.schema.org/2014/06/introducing-role.html).  We should try to be consistent with that as well.

**Comment by cboettig** [comment] 2020-04-09 00:04
@mbjones very true! Though my take on this is that we benefit more by being consistent with schema.org rather than creating a chimera.  This proposal is different, in that role would be an optional refinement/annotation of author, rather than a required field of "agent", which wasn't a CreativeWork property.  In general I am supportive of valid schema.org being valid codemeta; and particularly if this pattern is likely to be used in markup of similar objects like academic journals.  

Personally I'm still not a big fan of `role` codes in CRedit, in my own experience I always find them to be simultaneously too granular and too vague: it is often the case that one person takes a lead role in one aspect, say, documentation, and another in a different aspect, say, coding, but the coder does some writing and the documentation lead does some coding, so both get the same role codes (whether we're talking about software or journal articles).  But that's neither here nor there I suppose.  A nice thing about the above format is that a tool consuming codemeta (say, CiteAs) has the ability to ignore the role code refinement of 'author' if they want, while still being able to perform fundamental task like generating authorship list to create a citation.

**Comment by rdicosmo** [comment] 2020-04-13 08:56
@mbjones @cboettig quite happy to see that https://schema.org/role was already on the radar of previous discussions. The key observation is that roles are not properties of contributors, or of software, but of the relationship between contributors and software: #241 by @ProgVal is a way of implementing roles compliant to http://blog.schema.org/2014/06/introducing-role.html with minimal changes to CodeMeta.

By the way there is a similar issue with affiliations of persons: they are also properties that should not be attached to the persons, as they may change in time, unlike birthdates.

**Comment by rdicosmo** [comment] 2020-04-13 09:11
> Personally I'm still not a big fan of `role` codes in CRedit, in my own experience I always find them to be simultaneously too granular and too vague: it is often the case that one person takes a lead role in one aspect, say, documentation, and another in a different aspect, say, coding, but the coder does some writing and the documentation lead does some coding, so both get the same role codes (whether we're talking about software or journal articles). 

Fully agree with this observation: the same person may have different roles, with different levels of contribution, at the same time or at different times.
The paper mentioned at the beginning of this thread https://hal.archives-ouvertes.fr/hal-02135891 describes how Inria has been handling this internally.  For promotions/career evaluation, for example, researchers provide a self assessment of their level of contribution in each role:

_"Each contribution ranges from 1 (not involved) to 4 (main contributor). As an example, the personal contribution of one of OCaml’s main developer might be: Design and Architecture DA3, Coding and Debugging CD4, Maintenance and Support MS3, Team/Project Management TPM4."_

The 9 roles that are recommended in the article are a refinement/expansion of these 4, that take into account the needs that arise in other settings (e.g. tech transfer).

> A nice thing about the above format is that a tool consuming codemeta (say, CiteAs) has the ability to ignore the role code refinement of 'author' if they want, while still being able to perform fundamental task like generating authorship list to create a citation.

Absolutely! The idea is to have a way of representing this information in a canonical way in a CodeMeta document if/when it is available, and the consumers can drop it when not relevant.

**Comment by ljhwang** [comment] 2020-04-13 16:57
Is there support for these additional roles being a refinement to 'contributor' (or is this implied)?  For example in large software projects,  contributors  may have the same roles that the project wishes to acknowledged but the project may not want contributors picked up as authors e.g. the "CiteAs" example.

Is there a strawperson for the definition of these roles?  For example, in a recent discussion our group talked about community members who  actively engage in 'community building' and those who do not.  Such activities could fall into Support, Maintenance, & Management.  Fortunately, these can all be specified as a refinement of author but guidance would be good.

**Comment by rdicosmo** [comment] 2020-04-14 08:30
@ljhwang roles may be easily added to contributors too, with the same mechanism, if there is agreement on doing so.

**Comment by moranegg** [comment] 2020-04-27 21:08
> This makes sense to me as well. Is this pattern being used now to describe CRedit roles in schema.org descriptions of journal publications as well? It makes sense to me that we be as consistent as possible.

@cboettig I searched for the pattern, but didn't find a concrete example.
I have asked on multiple RDA mailing lists, without result.

@mbjones 's reference to science-on-schema.org group recommendations is a perfect example of how to use schema.org in research. The roles of people are implemented exactly like in the example in this issue. 

I think we can add the pattern in v3 without changing too much, since the pattern already exists in schema.org and it doesn't change the current usage of codemeta.json files.

We just need a couple of explained examples in the repo and webpage.

**Comment by moranegg** [comment] 2020-10-28 16:45
Hi @Nosferican, 
In the [MARC Code List for Relators](http://www.loc.gov/marc/relators/relaterm.html) I only found the following roles that are relative to different roles in the software creation process:

> Programmer [prg]
>     A person, family, or organization responsible for creating a computer program 

>  Designer [dsr]
>     A person, family, or organization responsible for creating a design for an object 

>  Architect [arc]
>     A person, family, or organization responsible for creating an architectural design, including a pictorial representation intended to show how a building, etc., will look when completed. It also oversees the construction of structures 


Alas, I haven't find roles for the following functions:
- Debugging
- Maintenance
- Documentation
- Testing
- Support
- Management

**Comment by moranegg** [comment] 2020-10-28 16:47
@mbjones, @cboettig, 
I think that the proposition in https://github.com/codemeta/codemeta/pull/241 is good for the v3 as is, do you have any comments on that? 
It might be a good time for @ProgVal to change the PR from draft to open.

**Comment by mbjones** [comment] 2020-10-28 18:41
@moranegg I think it looks good too. 

I'd like to retarget it to the `develop` branch and not work off master for releases anymore, because master is what shows on the website, and shouldn't be changed until we are ready to push the release. Soo... whoever merges it (maybe me), please merge it into develop and not master. 

Let's take this as a last call for comments on #241 and if there are no objections we'll merge it to develop in a couple of days.

**Comment by dgarijo** [comment] 2021-06-03 09:24
+1 to have roles, but optional. From the technical implementation, I do not understand quite well @moranegg's proposal here, because the `author` property is being overloaded:
```
"author": [
        {
            "@type": "Role",
            "roleName": "Design",
            "startDate": "2000",
            "endDate": "2002",
            "author": {
                "@type Person",
                "@id": "http://example.org/~jdupont",
...
```
Here the range of author is bot a role and a person, which is quite confusing. Why not the other way around?
```
"author": [
        {
           "@type Person",
           "@id": "http://example.org/~jdupont",
           "role": {
               "@type": "Role",
               "roleName": "Design",
               "startDate": "2000",
               "endDate": "2002",
            },
...
```   
Or to simplify even further, just have the roles without dates (e.g., making the  range of `role` a String or Role)

**Comment by ProgVal** [comment] 2021-06-03 09:54
@dgarijo It's not obvious here because we always encode Codemeta as a tree rooted in a single SoftwareSourceCode object, but you need to think of JSON-LD as a graph. Objects are nodes, and attributes are edges between these nodes.

In your first example, the graph looks like:

```
SoftwareSourceCode  <--->  Role  <--->  Person
```

so the Role is a relationship between the person and the code. (Or, put more pedantically, it reifies the edge between them in the graph).

In your second example, it is like this:

```
SoftwareSourceCode  <--->  Person  <--->  Role
```

so `Role` loses its relationship with the code; so roles no longer qualify a SoftwareSourceCode-Person relationship, they only qualify a Person.

**Comment by dgarijo** [comment] 2021-06-03 10:30
@ProgVal,
 
ah, I understand, role here is acting as an n-ary relationship. You are right in that converting to RDF the modeling would be wrong. However, how it's done in the proposal the `author` relationship is still overloaded

I would maybe introduce a "contributionRoles" property and do something similar to what @moranegg proposed:

```
"contributionRoles": [
        {
            "@type": "Role",
            "roleName": "Design",
            "startDate": "2000",
            "endDate": "2002",
            "by": {
                "@type Person",
                "@id": "http://example.org/~jdupont",
```
This way you can use authors/contributors/maintainers properties independently of the roles.

But this is still requires quite a bit of complexity. If codemeta is aiming for simplicity, I would argue against using reified statements.

**Comment by moranegg** [comment] 2023-02-16 13:26
This issue looks good and changes the spec, if no more comments are provided on the PR #241 until March 15th we will proceed with this issue to be a candidate for v3.0 or a future release

**Comment by broeder-j** [comment] 2023-03-17 07:42
Hi. Or why not instead (or in addition to) of contributionRoles introduce something like:

```
"contributions": [
        {
            "@type": "Code",
            ("roleName": "Developer",)
            "startDate": "2000",
            "endDate": "2002",
            "indentifiers" : [@type Mergerequest, @id url_to/commithash]
            "by/contributor": {
                "@type Person",
                "@id": "http://example.org/~jdupont",
```

this would allow for a shallow or deep representation of contributions code and non code wise. Shallow meaning X was a developer from year A to year B, Y a designer,... and deep meaning to really point to detailed contributions.
Also this allows for people having several types of contributions without overloading author or contributor.
Contributor in contributions could be an array, linking the same contribution to several contributors.

I do not know if there is already some closed vocabulary/standard for this. What I found so far is:

https://allcontributors.org/docs/en/emoji-key

**Comment by apirogov** [comment] 2023-03-24 10:34
Ok, I see. Might be a bit of abuse, but why not use `Person.performerIn`, represent the contribution as an `Event` (which also has start and end), and then use `Event.workPerformed` to point to a contribution description object, that is again a  (subclass of) `CreativeWork`? This would allow to use `releasedEvent` to point e.g. to git commits, `isPartOf` to point back to the whole software, and use `keywords` to tag the contribution with relevant "terms".

**Comment by dgarijo** [comment] 2023-03-24 15:38
@apirogov I think that the aim is to describe the contributor roles starting from a software record. If we start describing contributions at a person level, then we may need to return multiple objects in the json-ld file. Which in theory is fine.
If you have a concrete proposal, please add an example so we can discuss.
@moranegg I think we still need some discussion to reach consensus on this issue.

**Comment by stain** [comment] 2023-05-10 13:24
Here's one way for how we linked in roles in RO-Crate with schema.org using https://schema.org/Role as intermediary of `contributor`, with the roles marked as `additionalType` as they are just typed as `DefinedTerm` concepts.

Here the direct link to the person is also listed under `author` if considered for authorship:

(abridged)

```json
{
  "@context": "https://schema.org/",
  "@graph": [
    {
      "@id": "http://example.com/doc1",
      "@type": "CreativeWork",
      "author": [
        {
          "@id": "https://orcid.org/0000-0001-9842-9718"
        },
        {
          "@id": "https://orcid.org/0000-0002-3545-944X"
        }
      ],
      "contributor": [
        {
          "@id": "#role-0000-0001-9842-9718"
        },
        {
          "@id": "#role-0000-0002-3545-944X"
        }
      ]
    },
    {
      "@id": "#role-0000-0001-9842-9718",
      "@type": "Role",
      "additionalType": [
        {
          "@id": "http://purl.org/credit/ontology#CREDIT_00000001"
        },
        {
          "@id": "http://purl.org/credit/ontology#CREDIT_00000002"
        },
        {
          "@id": "http://purl.obolibrary.org/obo/CRO_0000051"
        }
      ],
      "contributor": {
        "@id": "https://orcid.org/0000-0001-9842-9718"
      },
      "name": "Contributions by Stian Soiland-Reyes"
    },
    {
      "@id": "#role-0000-0002-3545-944X",
      "@type": "Role",
      "additionalType": {
        "@id": "http://purl.org/credit/ontology#CREDIT_00000001"
      },
      "contributor": {
        "@id": "https://orcid.org/0000-0002-3545-944X"
      },
      "name": "Contributions by Peter Sefton"
    },
    {
      "@id": "http://purl.obolibrary.org/obo/CRO_0000051",
      "@type": "DefinedTerm",
      "name": "system administrator role"
    },
    {
      "@id": "http://purl.org/credit/ontology#CREDIT_00000001",
      "@type": "DefinedTerm",
      "name": "conceptualization role"
    },
    {
      "@id": "http://purl.org/credit/ontology#CREDIT_00000002",
      "@type": "DefinedTerm",
      "name": "data curation role"
    },
    {
      "@id": "https://orcid.org/0000-0001-9842-9718",
      "@type": "Person",
      "name": "Stian Soiland-Reyes"
    },
    {
      "@id": "https://orcid.org/0000-0002-3545-944X",
      "@type": "Person",
      "name": "Peter Sefton"
    }
  ]
}
```

With this convention there are no `contributor` that is not listed through a `Role` -- schema.org is ambivalent on this as you can insert a role into basically any property to make it n-ary (and probably break lots of things in doing so..).

Above using JSON-LD Flattened (`@graph` array) helps, with regards to where the otherwise duplicated `Person` entries should appear. There could become inconsistencies then depending on authorship or not; assuming Peter above is no longer an author but is a contributor with a role, in compacted form:

```json
{
  "@context": "https://schema.org/",
  "@id": "http://example.com/doc1",
  "@type": "CreativeWork",
  "author": {
    "@id": "https://orcid.org/0000-0001-9842-9718",
    "@type": "Person",
    "name": "Stian Soiland-Reyes"
  },
  "contributor": [
    {
      "@id": "#role-0000-0001-9842-9718",
      "@type": "Role",
      "additionalType": [
        {
          "@id": "http://purl.org/credit/ontology#CREDIT_00000001",
          "@type": "DefinedTerm",
          "name": "conceptualization role"
        },
        {
          "@id": "http://purl.org/credit/ontology#CREDIT_00000002",
          "@type": "DefinedTerm",
          "name": "data curation role"
        },
        {
          "@id": "http://purl.obolibrary.org/obo/CRO_0000051",
          "@type": "DefinedTerm",
          "name": "system administrator role"
        }
      ],
      "contributor": {
        "@id": "https://orcid.org/0000-0001-9842-9718"
      },
      "name": "Contributions by Stian Soiland-Reyes"
    },
    {
      "@id": "#role-0000-0002-3545-944X",
      "@type": "Role",
      "additionalType": {
        "@id": "http://purl.org/credit/ontology#CREDIT_00000001"
      },
      "contributor": {
        "@id": "https://orcid.org/0000-0002-3545-944X",
        "@type": "Person",
        "name": "Peter Sefton"
      },
      "name": "Contributions by Peter Sefton"
    }
  ]
}
```

**Comment by stain** [comment] 2023-05-10 13:48
At CollaborationsWorkshop 23 we just had a hackathon and sadly was not aware of this issue.

We drafted [SORTÆD: Software Role Taxonomy and Authorship Definition](https://sdruskat.net/software-authorship/) – similar to CASRAI CREDIT but for software. Takes a view on what can be considered as authorship.

I think the list of software roles we come up there in a day are not yet ideal anyway, and should be adjusted or aligned with the list being proposed in this issue.  Reproduced below:

Supervision
 : _Coordinates the project effort, possibly across organizational boundaries_
 : Examples: Coordinator, project manager, advisor, team leader

 Resources
 : _Provision and maintenance of resources used and exposed by the software project, like computational infrastructure and cloud systems_
 : Examples: System administrator, cloud manager

 Funding
 : _Acquisition or management of funding for effort and events that sustain the software_
 : Examples: Principal Investigator, work package leader

 Outreach
 : _Communication with end-users and stakeholders_
 : Examples: Training, community manager, user support

 Development
 : _Writing of the backend and frontend code as well as managing dependencies, making the software ready for release_
 : Examples: Programmer, maintainer, UX designer, release manager

 Data curation
 : _Integration of data in the software and ensures metadata is annotated and available_
 : Examples: Data provider, statician, data manager

 Testing
 : _Unit test, usability, integration tests, release test_
 : Examples: Reviewer, reporting user

 Documentation
 : _Writing of all documentation related to the software, including user guidelines, roadmapping_
 : Examples: Technical writer, metadata curator

 Conceptualisation
 : _Formulation of the idea and goals of the software, design of main features and functionalities_
 : Examples: Principal Investigator, Architect, graphical designer, release manager, requirement gathering


BTW, we also started a [mapping](https://docs.google.com/spreadsheets/d/1Q66KBLMTa0aV6y630DSrVxlo6swvblTn6NgzHvNZCnw/edit#gid=0) against CodeMeta and SCoRO to see the coverage, extends the [Contributor Roles crosswalk](https://doi.org/10.5281/zenodo.4767798). Looking at SCoRO and Contributor Roles I see many important and detailed roles, but there's also a need to make it digestable in more general categories.

**Comment by dgarijo** [comment] 2023-05-10 13:55
Since we are on the topic, in https://w3id.org/softwareCredit# we also created a set of roles for software credit, by extending doap and using some foaf terms. The granularity in some of these roles is quite low. Maybe we can include them too

**Comment by progval** [comment] 2023-05-25 13:49
If I'm not mistaken, this proposal doesn't disallow using `Person` directly in `author` and `contributor` relationships without a `Role`. @moranegg Is that correct?

We can even mix both in the same document. For example, the example provided by @moranegg in the top post could be turned into:

```json
{
    "@context": "https://doi.org/10.5063/schema/codemeta-2.0",
    "@type": "SoftwareSourceCode",
    "name": "Foo Software",
    "author": [
        {
          "@type Person",
          "@id": "http://example.org/~jdupont",
          "givenName": "John",
          "familyName": "Dupont",
          "affiliation": [
              {
                  "@type": "Organization",
                  "name": "CNRS"
              },
              {
                  "@type": "Organization",
                  "name": "Inria"
              },
              {
                  "@type": "Organization",
                  "name": "Université de Paris"
              }
            ]
        },
        {
            "@type": "Role",
            "roleName": "Design",
            "startDate": "2000",
            "endDate": "2002",
            "author":  {
              "@id": "http://example.org/~jdupont"
            }
        },
        {
            "@type": "Role",
            "roleName": "Coding",
            "startDate": "2000",
            "endDate": "2002",
            "author": {
                "@id": "http://example.org/~jdupont"
            }
        },
        {
            "@type": "Role",
            "roleName": "Documentation",
            "startDate": "2000",
            "endDate": "2002",
            "author": {
                "@id": "http://example.org/~jdupont"
            }
        }
    ]
}
```

This way, parsers can ignore Roles entirely (as long as the document contains both forms). Should Codemeta recommend doing that?

@dgarijo and @stain Would this address your concerns in https://github.com/codemeta/codemeta/issues/240#issuecomment-853766853 and https://github.com/codemeta/codemeta/issues/240#issuecomment-1542207465

**Comment by progval** [comment] 2023-06-12 19:04
Ah indeed, I forgot `author` is defined as a `@list`. Forget this proposal, then.

> . Now we have `author` and `contributor`, maybe we could have `funder`, `supervisor`, `owner`, etc.

Then either writers have to repeat the people between author/contributor and funder/supervisor/owner, or writers need to have an exhaustive list of properties like funder/supervisor/owner in order to compute the list of all authors.

> This has its limitations (no extra metadata like "person X was contributor through 2022-23", but everything becomes simpler.

I can't speak for the others behind the original proposal, but I think they considered that this metadata was worth the added complexity. @moranegg correct?

**Comment by progval** [comment] 2023-07-03 14:37
Done in #241

**Closed by progval** 2023-07-03 14:37 UTC

**Comment by dgarijo** [comment] 2024-09-21 17:23
@moranegg I think we need to add some examples in the documentation. As it is, using roles is one of the least clear metadata fields in CodeMeta (in my opinion) since you need the dual `author` or `contributor` property to declare them
